/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "is_I_X_C-test.check" instead.
 */

#include <check.h>

#line 1 "is_I_X_C-test.check"
#include "CheckSyntax.h"

START_TEST(is_I_X_C_test)
{
#line 4
	fail_unless(is_I_X_C('I') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('X') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('C') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('i') == 0, "is_I_X_C failed - output true for bad input");
	fail_unless(is_I_X_C('M') == 0, "is_I_X_C failed - output true for bad input");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, is_I_X_C_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
